// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: synchs/msg/blame.proto

package synchs

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BlameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlameTarget uint64 `protobuf:"varint,1,opt,name=blameTarget,proto3" json:"blameTarget,omitempty"` // Who are we blaming?
	View        uint64 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`               // In what view are we blaming this leader?
}

func (x *BlameData) Reset() {
	*x = BlameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlameData) ProtoMessage() {}

func (x *BlameData) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlameData.ProtoReflect.Descriptor instead.
func (*BlameData) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{0}
}

func (x *BlameData) GetBlameTarget() uint64 {
	if x != nil {
		return x.BlameTarget
	}
	return 0
}

func (x *BlameData) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

type Blame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlData    *BlameData `protobuf:"bytes,1,opt,name=BlData,proto3" json:"BlData,omitempty"`
	BlOrigin  uint64     `protobuf:"varint,2,opt,name=BlOrigin,proto3" json:"BlOrigin,omitempty"` // Who is sending the blame
	Signature []byte     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Blame) Reset() {
	*x = Blame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blame) ProtoMessage() {}

func (x *Blame) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blame.ProtoReflect.Descriptor instead.
func (*Blame) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{1}
}

func (x *Blame) GetBlData() *BlameData {
	if x != nil {
		return x.BlData
	}
	return nil
}

func (x *Blame) GetBlOrigin() uint64 {
	if x != nil {
		return x.BlOrigin
	}
	return 0
}

func (x *Blame) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Certificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signatures [][]byte `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Ids        []uint64 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{2}
}

func (x *Certificate) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *Certificate) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type NoProgressBlame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blame *Blame `protobuf:"bytes,1,opt,name=blame,proto3" json:"blame,omitempty"`
}

func (x *NoProgressBlame) Reset() {
	*x = NoProgressBlame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoProgressBlame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoProgressBlame) ProtoMessage() {}

func (x *NoProgressBlame) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoProgressBlame.ProtoReflect.Descriptor instead.
func (*NoProgressBlame) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{3}
}

func (x *NoProgressBlame) GetBlame() *Blame {
	if x != nil {
		return x.Blame
	}
	return nil
}

type EquivocationBlame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blame *Blame    `protobuf:"bytes,1,opt,name=blame,proto3" json:"blame,omitempty"`
	B1    *Proposal `protobuf:"bytes,2,opt,name=b1,proto3" json:"b1,omitempty"`
	B2    *Proposal `protobuf:"bytes,3,opt,name=b2,proto3" json:"b2,omitempty"`
}

func (x *EquivocationBlame) Reset() {
	*x = EquivocationBlame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquivocationBlame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquivocationBlame) ProtoMessage() {}

func (x *EquivocationBlame) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquivocationBlame.ProtoReflect.Descriptor instead.
func (*EquivocationBlame) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{4}
}

func (x *EquivocationBlame) GetBlame() *Blame {
	if x != nil {
		return x.Blame
	}
	return nil
}

func (x *EquivocationBlame) GetB1() *Proposal {
	if x != nil {
		return x.B1
	}
	return nil
}

func (x *EquivocationBlame) GetB2() *Proposal {
	if x != nil {
		return x.B2
	}
	return nil
}

type QuitView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlCert *Certificate `protobuf:"bytes,1,opt,name=BlCert,proto3" json:"BlCert,omitempty"`
}

func (x *QuitView) Reset() {
	*x = QuitView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_synchs_msg_blame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitView) ProtoMessage() {}

func (x *QuitView) ProtoReflect() protoreflect.Message {
	mi := &file_synchs_msg_blame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitView.ProtoReflect.Descriptor instead.
func (*QuitView) Descriptor() ([]byte, []int) {
	return file_synchs_msg_blame_proto_rawDescGZIP(), []int{5}
}

func (x *QuitView) GetBlCert() *Certificate {
	if x != nil {
		return x.BlCert
	}
	return nil
}

var File_synchs_msg_blame_proto protoreflect.FileDescriptor

var file_synchs_msg_blame_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x6c, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x19, 0x73,
	0x79, 0x6e, 0x63, 0x68, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x09, 0x42, 0x6c, 0x61, 0x6d,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x61, 0x6d,
	0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x69, 0x0a, 0x05, 0x42,
	0x6c, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x42, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x6c, 0x61, 0x6d, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x42, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x6c, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x42, 0x6c, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x0f, 0x4e, 0x6f, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6c, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x62, 0x6c,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x42, 0x6c, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x11,
	0x45, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x05, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x6c, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x62, 0x6c,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x62, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x02,
	0x62, 0x31, 0x12, 0x1d, 0x0a, 0x02, 0x62, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x02, 0x62,
	0x32, 0x22, 0x34, 0x0a, 0x08, 0x51, 0x75, 0x69, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x28, 0x0a,
	0x06, 0x42, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x06, 0x42, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x69, 0x74, 0x68, 0x79, 0x61, 0x62, 0x68, 0x61,
	0x74, 0x6b, 0x61, 0x6a, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x65, 0x32, 0x63, 0x2f, 0x6d,
	0x73, 0x67, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_synchs_msg_blame_proto_rawDescOnce sync.Once
	file_synchs_msg_blame_proto_rawDescData = file_synchs_msg_blame_proto_rawDesc
)

func file_synchs_msg_blame_proto_rawDescGZIP() []byte {
	file_synchs_msg_blame_proto_rawDescOnce.Do(func() {
		file_synchs_msg_blame_proto_rawDescData = protoimpl.X.CompressGZIP(file_synchs_msg_blame_proto_rawDescData)
	})
	return file_synchs_msg_blame_proto_rawDescData
}

var file_synchs_msg_blame_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_synchs_msg_blame_proto_goTypes = []interface{}{
	(*BlameData)(nil),         // 0: msg.BlameData
	(*Blame)(nil),             // 1: msg.Blame
	(*Certificate)(nil),       // 2: msg.Certificate
	(*NoProgressBlame)(nil),   // 3: msg.NoProgressBlame
	(*EquivocationBlame)(nil), // 4: msg.EquivocationBlame
	(*QuitView)(nil),          // 5: msg.QuitView
	(*Proposal)(nil),          // 6: msg.Proposal
}
var file_synchs_msg_blame_proto_depIdxs = []int32{
	0, // 0: msg.Blame.BlData:type_name -> msg.BlameData
	1, // 1: msg.NoProgressBlame.blame:type_name -> msg.Blame
	1, // 2: msg.EquivocationBlame.blame:type_name -> msg.Blame
	6, // 3: msg.EquivocationBlame.b1:type_name -> msg.Proposal
	6, // 4: msg.EquivocationBlame.b2:type_name -> msg.Proposal
	2, // 5: msg.QuitView.BlCert:type_name -> msg.Certificate
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_synchs_msg_blame_proto_init() }
func file_synchs_msg_blame_proto_init() {
	if File_synchs_msg_blame_proto != nil {
		return
	}
	file_synchs_msg_proposal_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_synchs_msg_blame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_synchs_msg_blame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_synchs_msg_blame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Certificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_synchs_msg_blame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoProgressBlame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_synchs_msg_blame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquivocationBlame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_synchs_msg_blame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_synchs_msg_blame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_synchs_msg_blame_proto_goTypes,
		DependencyIndexes: file_synchs_msg_blame_proto_depIdxs,
		MessageInfos:      file_synchs_msg_blame_proto_msgTypes,
	}.Build()
	File_synchs_msg_blame_proto = out.File
	file_synchs_msg_blame_proto_rawDesc = nil
	file_synchs_msg_blame_proto_goTypes = nil
	file_synchs_msg_blame_proto_depIdxs = nil
}
