// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: e2c/msg/proposal.proto

package e2c

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// All configuration aggregated here
type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A proposal contains the following
	Cmds      []*Command `protobuf:"bytes,1,rep,name=cmds,proto3" json:"cmds,omitempty"`
	Proposer  uint64     `protobuf:"varint,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Signature []byte     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2c_msg_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_e2c_msg_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_e2c_msg_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetCmds() []*Command {
	if x != nil {
		return x.Cmds
	}
	return nil
}

func (x *Proposal) GetProposer() uint64 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *Proposal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_e2c_msg_proposal_proto protoreflect.FileDescriptor

var file_e2c_msg_proposal_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x32, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x15, 0x65,
	0x32, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x12, 0x20, 0x0a, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x63, 0x6d,
	0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x69, 0x74, 0x68,
	0x79, 0x61, 0x62, 0x68, 0x61, 0x74, 0x6b, 0x61, 0x6a, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x62,
	0x65, 0x32, 0x63, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x65, 0x32, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_e2c_msg_proposal_proto_rawDescOnce sync.Once
	file_e2c_msg_proposal_proto_rawDescData = file_e2c_msg_proposal_proto_rawDesc
)

func file_e2c_msg_proposal_proto_rawDescGZIP() []byte {
	file_e2c_msg_proposal_proto_rawDescOnce.Do(func() {
		file_e2c_msg_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_e2c_msg_proposal_proto_rawDescData)
	})
	return file_e2c_msg_proposal_proto_rawDescData
}

var file_e2c_msg_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_e2c_msg_proposal_proto_goTypes = []interface{}{
	(*Proposal)(nil), // 0: msg.Proposal
	(*Command)(nil),  // 1: msg.Command
}
var file_e2c_msg_proposal_proto_depIdxs = []int32{
	1, // 0: msg.Proposal.cmds:type_name -> msg.Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_e2c_msg_proposal_proto_init() }
func file_e2c_msg_proposal_proto_init() {
	if File_e2c_msg_proposal_proto != nil {
		return
	}
	file_e2c_msg_command_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_e2c_msg_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_e2c_msg_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e2c_msg_proposal_proto_goTypes,
		DependencyIndexes: file_e2c_msg_proposal_proto_depIdxs,
		MessageInfos:      file_e2c_msg_proposal_proto_msgTypes,
	}.Build()
	File_e2c_msg_proposal_proto = out.File
	file_e2c_msg_proposal_proto_rawDesc = nil
	file_e2c_msg_proposal_proto_goTypes = nil
	file_e2c_msg_proposal_proto_depIdxs = nil
}
